from util import *
import numpy as np

s = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
""".strip()
s = open("input.txt").read()

g, n, m = grid_from_string(s)

@cache
def dfs(depth, n, m):
    if depth == n:
        return 1

    total = 0
    if g[depth][m] == "^":
        total += dfs(depth + 1, n, m - 1)
        total += dfs(depth + 1, n, m + 1)
    elif g[depth][m] == ".":
        total += dfs(depth + 1, n, m)
    return total



print(dfs(1, n, m // 2))

